files:
  csv: assets/reports/vergunningen-2025/data/graph_data_clean.csv
  html: assets/reports/vergunningen-2025/charts/sloop/sloop.html
slug: vergunningen-2025-charts-sloop
summary: Interactieve grafiek van vergunningsaanvragen voor sloop in Vlaanderen
tags:
- vergunningen
- sloop
- Vlaanderen
- '2025'
title: Vergunningsaanvragen Sloop
type: interactive
